theme: jekyll-theme-slate
title: ‘Hello World’ Application with Spring Boot Microservice Stack
description: Simple microservice application designed to illustrate the basic concept of Microservice Architecture 
